forum/urls/urls.py
from django.conf.urls import patterns, include, url
from forum import views

urlpatterns = patterns(
    '',
    url( # Site Index
        regex=r'^$',
        view=views.Index.as_view(),
        name='index'
    ),
    url( # Creates a new forum
        regex=r'^create/$',
        view=views.ForumCreate.as_view(),
        name='forum_create'
    ),
    url( # Update a forum
        regex=r'^f/(?P<forum_slug>[-\w]+)/admin/$',
        view=views.ForumUpdate.as_view(),
        name='forum_update'
    ),
    url( # View a forum
        regex=r'^f/(?P<forum_slug>[-\w]+)/$',
        view=views.ForumDetail.as_view(),
        name='forum_detail'
    ),
    url( # Create a thread
        regex=r'^f/(?P<forum_slug>[-\w]+)/create/$',
        view=views.ThreadCreate.as_view(),
        name="thread_create"
    ),
    url( # Update a thread
        regex=r'^f/(?P<forum_slug>[-\w]+)/(?P<thread_slug>[-\w]+)/update/$',
        view=views.ThreadUpdate.as_view(),
        name="thread_create"
    ),    
    url( # link to a thread
        regex=r'^f/(?P<forum_slug>[-\w]+)/(?P<thread_slug>[-\w]+)/$',
        view=views.ThreadDetail.as_view(),
        name="thread_detail"
    ),
    url( # create a post
        regex=r'^f/(?P<forum_slug>[-\w]+)/(?P<thread_slug>[-\w]+)/reply/$',
        view=views.PostCreate.as_view(),
        name="thread_reply"
    ),     
    url( # create a post
        regex=r'^f/(?P<forum_slug>[-\w]+)/(?P<thread_slug>[-\w]+)/(?P<post_id>[-\w]+)/reply/$',
        view=views.PostCreate.as_view(),
        name="post_reply"
    ),     
    url( # link to a post
        regex=r'^p/(?P<post_id>[-\w]+)/$',
        view=views.PostDetail.as_view(),
        name="post_detail"
    ),
    url( # edit a post
        regex=r'^p/(?P<post_id>[-\w]+)/update/$',
        view=views.PostUpdate.as_view(),
        name="post_update"
    ),    
)

forum/models/forum.py
from datetime import datetime
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils.text import slugify


class Forum(models.Model):
    name = models.CharField(unique=True, max_length=254)
    forum_slug = models.SlugField(unique=True, max_length=254, editable=False)
    description = models.TextField()
    created = models.DateField(blank=True, null=True, editable=False)
    modified = models.DateField(blank=True, null=True, editable=False)
    moderators = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="moderators")

    class Meta:
        app_label = 'forum'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('forum:forum_detail',
                       kwargs={'forum_slug': self.forum_slug})

    def save(self, *args, **kwargs):
        if not self.id:
            self.created = datetime.now()
            self.forum_slug = slugify(self.name)
        self.modified = datetime.now()
        super(Forum, self).save(*args, **kwargs)

forum/models/post.py
from datetime import datetime
from uuid import uuid4
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from mptt.models import MPTTModel, TreeForeignKey

from forum.models.thread import Thread


class Post(MPTTModel):
    thread = models.ForeignKey(Thread, verbose_name='thread')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="user")
    parent = TreeForeignKey('self', blank=True, null=True, related_name="children")
    created = models.DateField(blank=True, null=True, editable=False)
    modified = models.DateField(blank=True, null=True, editable=False)
    post_id = models.CharField(unique=True, max_length=45, editable=False)
    text = models.TextField()
    vote_up_count = models.IntegerField(default=0, editable=False)
    vote_down_count = models.IntegerField(default=0, editable=False)

    class Meta:
        app_label = 'forum'
    
    def __str__(self):
        return self.post_id

    def get_absolute_url(self):
        return reverse('forum:post_detail', kwargs={'post_id': self.post_id})

    def save(self, *args, **kwargs):
        if not self.id:
            self.created = datetime.now()
            yyyymmdd = self.created.strftime('%Y%m%d')
            self.post_id = yyyymmdd + "-" + str(uuid4())
        self.modified = datetime.now()
        super(Post, self).save(*args, **kwargs)

    def score(self):
        return "%s" % (self.vote_up_count - self.vote_down_count)

forum/models/thread.py
from datetime import datetime
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils.text import slugify

from forum.models.forum import Forum


class Thread(models.Model):
    forum = models.ForeignKey(Forum, verbose_name='forum')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="user")    
    name = models.CharField(max_length=254)
    thread_slug = models.SlugField(max_length=254, editable=False)
    description = models.TextField()
    vote_up_count = models.IntegerField(default=0, editable=False)
    vote_down_count = models.IntegerField(default=0, editable=False)
    created = models.DateField(blank=True, null=True, editable=False)
    modified = models.DateField(blank=True, null=True, editable=False)
    
    class Meta:
        app_label = 'forum'
        unique_together = ('forum', 'thread_slug')    

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('forum:thread_detail',
                       kwargs={'thread_slug': self.thread_slug,
                               'forum_slug': self.forum.forum_slug,})

    def save(self, *args, **kwargs):
            if not self.id:
                self.created = datetime.now()
                yyyymmdd = self.created.strftime('%Y%m%d')
                self.thread_slug = yyyymmdd + "-" + slugify(self.name)
            self.modified = datetime.now()
            super(Thread, self).save(*args, **kwargs)

forum/views/forum.py
from django.views import generic
from braces.views import LoginRequiredMixin
from forum.models.forum import Forum
from forum.forms import ForumForm


class ForumDetail(generic.DetailView):
    model = Forum
    slug_field = 'forum_slug'
    slug_url_kwarg = 'forum_slug'


class ForumList(generic.ListView):
    model = Forum
    paginate_by = 25


class ForumCreate(LoginRequiredMixin, generic.CreateView):
    model = Forum
    form_class = ForumForm

    def get_form_kwargs(self):
        kwargs = super(ForumCreate, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class ForumUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Forum
    form_class = ForumForm
    slug_field = 'forum_slug'
    slug_url_kwarg = 'forum_slug'
    
    def get_form_kwargs(self):
        kwargs = super(ForumUpdate, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs    

forum/views/post.py
from django.views import generic
from braces.views import LoginRequiredMixin
from forum.models.forum import Forum
from forum.models.thread import Thread
from forum.models.post import Post
from forum.forms import PostForm

class PostDetail(generic.DetailView):
    model = Post
    slug_field = 'post_id'
    slug_url_kwarg = 'post_id'


class PostCreate(LoginRequiredMixin, generic.CreateView):
    model = Post
    form_class = PostForm
    
    def get_form_kwargs(self):
        kwargs = super(PostCreate, self).get_form_kwargs()
        kwargs['thread'] = Thread.objects.get(
            forum=Forum.objects.get(forum_slug=self.kwargs['forum_slug']),
            thread_slug=self.kwargs['thread_slug'])
        kwargs['user'] = self.request.user
        if 'post_id' in self.kwargs:
            kwargs['parent'] = Post.objects.get(post_id=self.kwargs['post_id'])
        else:
            kwargs['parent'] = None
        return kwargs        


class PostUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Post
    form_class = PostForm

forum/views/thread.py
from django.views import generic
from braces.views import LoginRequiredMixin
from forum.models.forum import Forum
from forum.models.thread import Thread
from forum.models.post import Post
from forum.forms import ThreadForm


class ThreadDetail(generic.TemplateView):
    template_name = 'forum/thread_detail.html'
        
    def get_context_data(self, **kwargs):
        context = super(ThreadDetail, self).get_context_data(**kwargs)
        self.object = Thread.objects.get(
            forum=Forum.objects.get(forum_slug=self.kwargs['forum_slug']),
            thread_slug=self.kwargs['thread_slug'])
        context['thread'] = self.object
        context['thread_posts'] = Post.objects.filter(
            thread = self.object)
        return context    


class ThreadList(generic.ListView):
    model = Thread
    paginate_by = 25
    

class ThreadCreate(LoginRequiredMixin, generic.CreateView):
    model = Thread
    form_class = ThreadForm
    
    def get_form_kwargs(self):
        kwargs = super(ThreadCreate, self).get_form_kwargs()
        kwargs['forum'] = Forum.objects.get(forum_slug=self.kwargs['forum_slug'])
        kwargs['user'] = self.request.user
        return kwargs        


class ThreadUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Thread
    form_class = ThreadForm
    # this will be tricky....

forum/templates/forum/forum_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ forum.name }}
{% endblock %}

{% block content %}
    <h1>{{ forum.name }}</h1>
    <p>{{ forum.description }}</p>
    
    {% for thread in forum.thread_set.all  %}
      <ul>
        <li><a href="{{ thread.get_absolute_url }}">{{ thread.name }}</a>  by {{ thread.user }}</li>
      </ul>
    {% endfor %}
    
        <h1>Create a new Thread</h1>
        <a href="{% url 'forum:thread_create' forum.forum_slug %}">Create a new thread</a>
{% endblock %}

forum/templates/forum/forum_form.html
<form action="." method="post">{% csrf_token %}
  <table class="table">
    {{ form }}
  </table>
  <input type="submit" value="Submit" />
</form>

forum/templates/forum/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Hello {{ user }}!</h1>
    
    {% for f in forums %}
        <ul>
            <li>
                <a href="{{ f.get_absolute_url }}">{{ f }}</a>
            </li>
        </ul>
    {% endfor %}
    
    <h1>Create a new forum</h1>
    <a href="{% url 'forum:forum_create' %}">Create a new forum</a>
{% endblock %}

forum/templates/forum/post_detail.html
{% extends 'base.html' %}

{% block content %}

    <p>{{ post.text }}</p>
    
{% endblock %}

forum/templates/forum/post_form.html
{% extends 'base.html' %}

{% block content %}
<form action="." method="post">{% csrf_token %}
  <table class="table">
    {{ form }}
  </table>
  <input type="submit" value="Submit" />
</form>
{% endblock %}

forum/templates/forum/thread_detail.html
{% extends 'base.html' %}
{% load mptt_tags %}

{% block title %}
  {{ thread.name }} : {{ thread.forum.name }}
{% endblock %}

{% block extra_js %}
  <script>
  function vote(post_id, vote_type){
    $.ajax({
        url: 'http://127.0.0.1:8000/forum/vote/',
        type: "POST",
        datatype: "json",
        async: "true",
        data:{
            csrfmiddlewaretoken: "{{ csrf_token }}",
            vote: vote_type,
            id: post_id,
        },
        success: function(data) {
            alert(data);
        },
        failure: function(data) { 
            alert('Got an error dude');
        }
    });
  }
  </script>
{% endblock %}

{% block content %}
  <h1>{{ thread.name }}</h1>
  <p>{{ thread.description }}</p>
  <a class="btn btn-default" href="{% url 'forum:thread_reply' thread.forum.forum_slug thread.thread_slug %}">Reply to Thread</a>
  <ul class="list-group">
    {% recursetree thread_posts %}
        <li class="list-group-item">
          <form id="{{node.post_id}}">
            <button type="button"
                    class="btn btn-default btn-sm"
                    role="button"
                    value="up"
                    onclick="vote(this.form.id, this.value)">
              <span class="glyphicon glyphicon-ok"></span>
            </button>
            <button type="button"
                    class="btn btn-default btn-sm"
                    role="button" value="down"
                    onclick="vote(this.form.id, this.value)">
              <span class="glyphicon glyphicon-remove"></span>
            </button>
          </form>
          <p><small>{{ node.user }} - {{ node.score }} points - {{ node.modified }}</small></p>
          <p>{{ node.text }}</p>
          <a class="btn btn-default btn-sm" 
             href="{{ node.get_absolute_url }}">Permalink</a>
          <a class="btn btn-default btn-sm" 
             href="{% url 'forum:post_reply' thread.forum.forum_slug thread.thread_slug node.post_id %}">Reply</a>
          {% if not node.is_leaf_node %}
              <ul class="list-group children">
                  {{ children }}
              </ul>
          {% endif %}
        </li>
    {% endrecursetree %}
  </ul>
{% endblock %}

forum/templates/forum/thread_form.html
{% extends 'base.html' %}

{% block content %}
<form action="." method="post">{% csrf_token %}
  <table class="table">
    {{ form }}
  </table>
  <input type="submit" value="Submit" />
</form>
{% endblock %}